spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
